export const SHOWCASE_ICONS = [
  "MenuIcon",
  "SettingsIcon",
  "SendIcon",
  "ArrowLeftIcon",
  "PlusIcon",
  "XIcon",
  "ChevronDownIcon",
  "ChevronLeftIcon",
  "ChevronRightIcon",
  "ChevronUpIcon",
  "RefreshIcon",
  "EditIcon",
  "ImageIcon",
  "StopIcon",
  "DownloadIcon",
  "AttachIcon",
  "PawIcon",
  "CheckIcon",
  "CheckCircleIcon",
  "AlertCircleIcon",
  "AlertTriangleIcon",
  "InfoIcon",
  "DotIcon",
  "SearchIcon",
  "CopyIcon",
  "MoreHorizontalIcon",
  "LoaderIcon",
] as const;

export type ShowcaseIconNameT = (typeof SHOWCASE_ICONS)[number];
